[build-system]
requires = ["uv_build>=0.12.9,<0.13"]
build-backend = "uv_build"

[project]
name = "comet"
version = "1.7.0"
description = "Control and Measurement Toolkit"
authors = [
  {name = "Bernhard Arnold", email = "bernhard.arnold@oeaw.ac.at"},
]
readme = "README.md"
license = {text = "GPLv3"}
requires-python = ">=3.11"
dependencies = [
    "PyVISA",
    "PyVISA-py",
    "PyVISA-sim",
    "pyserial",
    "pyusb",
    "numpy",
    "schema",
    "PyYAML",
]

[project.urls]
Homepage = "https://hephy-dd.github.io/comet/"
Source = "https://github.com/hephy-dd/comet/"

[project.scripts]
comet-emulator = "comet.emulator.__main__:main"

[tool.ruff.lint]
extend-ignore = ["BLE001", "RUF022"]

[tool.basedpyright]
typeCheckingMode = "standard"
